# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/add.ui'
#
# Created: Thu Aug 19 16:30:31 2010
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_AddDive(object):
    def setupUi(self, AddDive):
        AddDive.setObjectName("AddDive")
        AddDive.resize(462, 580)
        self.centralwidget = QtGui.QWidget(AddDive)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.LNumber = QtGui.QLabel(self.centralwidget)
        self.LNumber.setObjectName("LNumber")
        self.horizontalLayout_8.addWidget(self.LNumber)
        self.INumber = QtGui.QLineEdit(self.centralwidget)
        self.INumber.setObjectName("INumber")
        self.horizontalLayout_8.addWidget(self.INumber)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.LLocation = QtGui.QLabel(self.centralwidget)
        self.LLocation.setObjectName("LLocation")
        self.horizontalLayout_7.addWidget(self.LLocation)
        self.ILocation = QtGui.QLineEdit(self.centralwidget)
        self.ILocation.setObjectName("ILocation")
        self.horizontalLayout_7.addWidget(self.ILocation)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.LDate = QtGui.QLabel(self.centralwidget)
        self.LDate.setObjectName("LDate")
        self.horizontalLayout_6.addWidget(self.LDate)
        self.IDate = QtGui.QDateEdit(self.centralwidget)
        self.IDate.setCalendarPopup(True)
        self.IDate.setObjectName("IDate")
        self.horizontalLayout_6.addWidget(self.IDate)
        self.LFormatDate = QtGui.QLabel(self.centralwidget)
        self.LFormatDate.setObjectName("LFormatDate")
        self.horizontalLayout_6.addWidget(self.LFormatDate)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.LTimeIn = QtGui.QLabel(self.centralwidget)
        self.LTimeIn.setObjectName("LTimeIn")
        self.horizontalLayout_5.addWidget(self.LTimeIn)
        self.ITimeIn = QtGui.QTimeEdit(self.centralwidget)
        self.ITimeIn.setObjectName("ITimeIn")
        self.horizontalLayout_5.addWidget(self.ITimeIn)
        self.LTimeOut = QtGui.QLabel(self.centralwidget)
        self.LTimeOut.setObjectName("LTimeOut")
        self.horizontalLayout_5.addWidget(self.LTimeOut)
        self.ITimeOut = QtGui.QTimeEdit(self.centralwidget)
        self.ITimeOut.setObjectName("ITimeOut")
        self.horizontalLayout_5.addWidget(self.ITimeOut)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.LTime = QtGui.QLabel(self.centralwidget)
        self.LTime.setObjectName("LTime")
        self.horizontalLayout_4.addWidget(self.LTime)
        self.ITime = QtGui.QLineEdit(self.centralwidget)
        self.ITime.setObjectName("ITime")
        self.horizontalLayout_4.addWidget(self.ITime)
        self.LDiveTime = QtGui.QLabel(self.centralwidget)
        self.LDiveTime.setWordWrap(True)
        self.LDiveTime.setObjectName("LDiveTime")
        self.horizontalLayout_4.addWidget(self.LDiveTime)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LBarIn = QtGui.QLabel(self.centralwidget)
        self.LBarIn.setObjectName("LBarIn")
        self.horizontalLayout_3.addWidget(self.LBarIn)
        self.IBarIn = QtGui.QSpinBox(self.centralwidget)
        self.IBarIn.setMaximum(350)
        self.IBarIn.setProperty("value", QtCore.QVariant(220))
        self.IBarIn.setObjectName("IBarIn")
        self.horizontalLayout_3.addWidget(self.IBarIn)
        self.LBarOut = QtGui.QLabel(self.centralwidget)
        self.LBarOut.setObjectName("LBarOut")
        self.horizontalLayout_3.addWidget(self.LBarOut)
        self.IBarOut = QtGui.QSpinBox(self.centralwidget)
        self.IBarOut.setMaximum(350)
        self.IBarOut.setProperty("value", QtCore.QVariant(50))
        self.IBarOut.setObjectName("IBarOut")
        self.horizontalLayout_3.addWidget(self.IBarOut)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LDepth = QtGui.QLabel(self.centralwidget)
        self.LDepth.setObjectName("LDepth")
        self.horizontalLayout_2.addWidget(self.LDepth)
        self.IDepth = QtGui.QDoubleSpinBox(self.centralwidget)
        self.IDepth.setProperty("value", QtCore.QVariant(10.0))
        self.IDepth.setObjectName("IDepth")
        self.horizontalLayout_2.addWidget(self.IDepth)
        self.LLead = QtGui.QLabel(self.centralwidget)
        self.LLead.setObjectName("LLead")
        self.horizontalLayout_2.addWidget(self.LLead)
        self.ILead = QtGui.QSpinBox(self.centralwidget)
        self.ILead.setProperty("value", QtCore.QVariant(8))
        self.ILead.setObjectName("ILead")
        self.horizontalLayout_2.addWidget(self.ILead)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LTemperature = QtGui.QLabel(self.centralwidget)
        self.LTemperature.setObjectName("LTemperature")
        self.horizontalLayout.addWidget(self.LTemperature)
        self.ITemperature = QtGui.QSpinBox(self.centralwidget)
        self.ITemperature.setMinimum(-100)
        self.ITemperature.setMaximum(100)
        self.ITemperature.setProperty("value", QtCore.QVariant(10))
        self.ITemperature.setObjectName("ITemperature")
        self.horizontalLayout.addWidget(self.ITemperature)
        self.LSight = QtGui.QLabel(self.centralwidget)
        self.LSight.setObjectName("LSight")
        self.horizontalLayout.addWidget(self.LSight)
        self.ISight = QtGui.QSpinBox(self.centralwidget)
        self.ISight.setProperty("value", QtCore.QVariant(5))
        self.ISight.setObjectName("ISight")
        self.horizontalLayout.addWidget(self.ISight)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.LNotes = QtGui.QLabel(self.centralwidget)
        self.LNotes.setObjectName("LNotes")
        self.verticalLayout.addWidget(self.LNotes)
        self.INotes = QtGui.QTextEdit(self.centralwidget)
        self.INotes.setObjectName("INotes")
        self.verticalLayout.addWidget(self.INotes)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.Add = QtGui.QPushButton(self.centralwidget)
        self.Add.setObjectName("Add")
        self.horizontalLayout_9.addWidget(self.Add)
        self.Cancel = QtGui.QPushButton(self.centralwidget)
        self.Cancel.setObjectName("Cancel")
        self.horizontalLayout_9.addWidget(self.Cancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        AddDive.setCentralWidget(self.centralwidget)

        self.retranslateUi(AddDive)
        QtCore.QMetaObject.connectSlotsByName(AddDive)

    def retranslateUi(self, AddDive):
        AddDive.setWindowTitle(QtGui.QApplication.translate("AddDive", "Add a Dive", None, QtGui.QApplication.UnicodeUTF8))
        self.LNumber.setText(QtGui.QApplication.translate("AddDive", "Dive Number", None, QtGui.QApplication.UnicodeUTF8))
        self.LLocation.setText(QtGui.QApplication.translate("AddDive", "Location        ", None, QtGui.QApplication.UnicodeUTF8))
        self.LDate.setText(QtGui.QApplication.translate("AddDive", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.IDate.setDisplayFormat(QtGui.QApplication.translate("AddDive", "yyyy-MM-dd", None, QtGui.QApplication.UnicodeUTF8))
        self.LFormatDate.setText(QtGui.QApplication.translate("AddDive", "Format: YYYY-MM-DD                          ", None, QtGui.QApplication.UnicodeUTF8))
        self.LTimeIn.setText(QtGui.QApplication.translate("AddDive", "Time In", None, QtGui.QApplication.UnicodeUTF8))
        self.ITimeIn.setDisplayFormat(QtGui.QApplication.translate("AddDive", "hh:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LTimeOut.setText(QtGui.QApplication.translate("AddDive", "Time Out", None, QtGui.QApplication.UnicodeUTF8))
        self.ITimeOut.setDisplayFormat(QtGui.QApplication.translate("AddDive", "hh:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LTime.setText(QtGui.QApplication.translate("AddDive", "Dive Time     ", None, QtGui.QApplication.UnicodeUTF8))
        self.LDiveTime.setText(QtGui.QApplication.translate("AddDive", "If time/out filled in not needed", None, QtGui.QApplication.UnicodeUTF8))
        self.LBarIn.setText(QtGui.QApplication.translate("AddDive", "Bar In", None, QtGui.QApplication.UnicodeUTF8))
        self.LBarOut.setText(QtGui.QApplication.translate("AddDive", "Bar Out", None, QtGui.QApplication.UnicodeUTF8))
        self.LDepth.setText(QtGui.QApplication.translate("AddDive", "Depth", None, QtGui.QApplication.UnicodeUTF8))
        self.LLead.setText(QtGui.QApplication.translate("AddDive", "Lead", None, QtGui.QApplication.UnicodeUTF8))
        self.LTemperature.setText(QtGui.QApplication.translate("AddDive", "Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.LSight.setText(QtGui.QApplication.translate("AddDive", "Sight", None, QtGui.QApplication.UnicodeUTF8))
        self.LNotes.setText(QtGui.QApplication.translate("AddDive", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.Add.setText(QtGui.QApplication.translate("AddDive", "Add Dive", None, QtGui.QApplication.UnicodeUTF8))
        self.Cancel.setText(QtGui.QApplication.translate("AddDive", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

