# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/add.ui'
#
# Created: Wed Aug 18 16:06:26 2010
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_AddDive(object):
    def setupUi(self, AddDive):
        AddDive.setObjectName("AddDive")
        AddDive.resize(543, 607)
        self.centralwidget = QtGui.QWidget(AddDive)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.NumberLay = QtGui.QHBoxLayout()
        self.NumberLay.setObjectName("NumberLay")
        self.LNumber = QtGui.QLabel(self.centralwidget)
        self.LNumber.setObjectName("LNumber")
        self.NumberLay.addWidget(self.LNumber)
        self.INumber = QtGui.QLineEdit(self.centralwidget)
        self.INumber.setObjectName("INumber")
        self.NumberLay.addWidget(self.INumber)
        self.verticalLayout.addLayout(self.NumberLay)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LLocation = QtGui.QLabel(self.centralwidget)
        self.LLocation.setObjectName("LLocation")
        self.horizontalLayout.addWidget(self.LLocation)
        self.ILocation = QtGui.QLineEdit(self.centralwidget)
        self.ILocation.setObjectName("ILocation")
        self.horizontalLayout.addWidget(self.ILocation)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.DateLay = QtGui.QHBoxLayout()
        self.DateLay.setObjectName("DateLay")
        self.LDate = QtGui.QLabel(self.centralwidget)
        self.LDate.setObjectName("LDate")
        self.DateLay.addWidget(self.LDate)
        self.IDate = QtGui.QDateEdit(self.centralwidget)
        self.IDate.setCalendarPopup(True)
        self.IDate.setObjectName("IDate")
        self.DateLay.addWidget(self.IDate)
        self.LFormatDate = QtGui.QLabel(self.centralwidget)
        self.LFormatDate.setObjectName("LFormatDate")
        self.DateLay.addWidget(self.LFormatDate)
        self.verticalLayout.addLayout(self.DateLay)
        self.TimeLay = QtGui.QHBoxLayout()
        self.TimeLay.setObjectName("TimeLay")
        self.LTimeIn = QtGui.QLabel(self.centralwidget)
        self.LTimeIn.setObjectName("LTimeIn")
        self.TimeLay.addWidget(self.LTimeIn)
        self.ITimeIn = QtGui.QTimeEdit(self.centralwidget)
        self.ITimeIn.setMaximumTime(QtCore.QTime(23, 59, 59))
        self.ITimeIn.setCurrentSection(QtGui.QDateTimeEdit.HourSection)
        self.ITimeIn.setCurrentSectionIndex(0)
        self.ITimeIn.setTimeSpec(QtCore.Qt.LocalTime)
        self.ITimeIn.setObjectName("ITimeIn")
        self.TimeLay.addWidget(self.ITimeIn)
        self.LTimeOut = QtGui.QLabel(self.centralwidget)
        self.LTimeOut.setObjectName("LTimeOut")
        self.TimeLay.addWidget(self.LTimeOut)
        self.ITimeOut = QtGui.QTimeEdit(self.centralwidget)
        self.ITimeOut.setMaximumTime(QtCore.QTime(23, 59, 59))
        self.ITimeOut.setCurrentSection(QtGui.QDateTimeEdit.HourSection)
        self.ITimeOut.setCurrentSectionIndex(0)
        self.ITimeOut.setTimeSpec(QtCore.Qt.LocalTime)
        self.ITimeOut.setObjectName("ITimeOut")
        self.TimeLay.addWidget(self.ITimeOut)
        self.verticalLayout.addLayout(self.TimeLay)
        self.BarLay = QtGui.QHBoxLayout()
        self.BarLay.setObjectName("BarLay")
        self.LBarIn = QtGui.QLabel(self.centralwidget)
        self.LBarIn.setObjectName("LBarIn")
        self.BarLay.addWidget(self.LBarIn)
        self.IBarIn = QtGui.QSpinBox(self.centralwidget)
        self.IBarIn.setMaximum(300)
        self.IBarIn.setProperty("value", QtCore.QVariant(220))
        self.IBarIn.setObjectName("IBarIn")
        self.BarLay.addWidget(self.IBarIn)
        self.LBarOut = QtGui.QLabel(self.centralwidget)
        self.LBarOut.setObjectName("LBarOut")
        self.BarLay.addWidget(self.LBarOut)
        self.IBarOut = QtGui.QSpinBox(self.centralwidget)
        self.IBarOut.setMaximum(300)
        self.IBarOut.setProperty("value", QtCore.QVariant(50))
        self.IBarOut.setObjectName("IBarOut")
        self.BarLay.addWidget(self.IBarOut)
        self.verticalLayout.addLayout(self.BarLay)
        self.TempSightLay = QtGui.QHBoxLayout()
        self.TempSightLay.setObjectName("TempSightLay")
        self.Ltemperature = QtGui.QLabel(self.centralwidget)
        self.Ltemperature.setObjectName("Ltemperature")
        self.TempSightLay.addWidget(self.Ltemperature)
        self.ITemperature = QtGui.QSpinBox(self.centralwidget)
        self.ITemperature.setMinimum(-99)
        self.ITemperature.setProperty("value", QtCore.QVariant(20))
        self.ITemperature.setObjectName("ITemperature")
        self.TempSightLay.addWidget(self.ITemperature)
        self.LSight = QtGui.QLabel(self.centralwidget)
        self.LSight.setObjectName("LSight")
        self.TempSightLay.addWidget(self.LSight)
        self.ISight = QtGui.QSpinBox(self.centralwidget)
        self.ISight.setProperty("value", QtCore.QVariant(10))
        self.ISight.setObjectName("ISight")
        self.TempSightLay.addWidget(self.ISight)
        self.verticalLayout.addLayout(self.TempSightLay)
        self.LeadLay = QtGui.QHBoxLayout()
        self.LeadLay.setObjectName("LeadLay")
        self.LLead = QtGui.QLabel(self.centralwidget)
        self.LLead.setObjectName("LLead")
        self.LeadLay.addWidget(self.LLead)
        self.ILead = QtGui.QSpinBox(self.centralwidget)
        self.ILead.setProperty("value", QtCore.QVariant(8))
        self.ILead.setObjectName("ILead")
        self.LeadLay.addWidget(self.ILead)
        self.verticalLayout.addLayout(self.LeadLay)
        self.DepthLay = QtGui.QHBoxLayout()
        self.DepthLay.setObjectName("DepthLay")
        self.Ldepth = QtGui.QLabel(self.centralwidget)
        self.Ldepth.setObjectName("Ldepth")
        self.DepthLay.addWidget(self.Ldepth)
        self.IDepth = QtGui.QDoubleSpinBox(self.centralwidget)
        self.IDepth.setProperty("value", QtCore.QVariant(10.0))
        self.IDepth.setObjectName("IDepth")
        self.DepthLay.addWidget(self.IDepth)
        self.verticalLayout.addLayout(self.DepthLay)
        self.DiveTimeLay = QtGui.QHBoxLayout()
        self.DiveTimeLay.setObjectName("DiveTimeLay")
        self.LTime = QtGui.QLabel(self.centralwidget)
        self.LTime.setObjectName("LTime")
        self.DiveTimeLay.addWidget(self.LTime)
        self.ITime = QtGui.QLineEdit(self.centralwidget)
        self.ITime.setObjectName("ITime")
        self.DiveTimeLay.addWidget(self.ITime)
        self.LFormatTime = QtGui.QLabel(self.centralwidget)
        self.LFormatTime.setWordWrap(True)
        self.LFormatTime.setObjectName("LFormatTime")
        self.DiveTimeLay.addWidget(self.LFormatTime)
        self.verticalLayout.addLayout(self.DiveTimeLay)
        self.Noteslay = QtGui.QVBoxLayout()
        self.Noteslay.setObjectName("Noteslay")
        self.LNotes = QtGui.QLabel(self.centralwidget)
        self.LNotes.setObjectName("LNotes")
        self.Noteslay.addWidget(self.LNotes)
        self.INotes = QtGui.QTextEdit(self.centralwidget)
        self.INotes.setObjectName("INotes")
        self.Noteslay.addWidget(self.INotes)
        self.verticalLayout.addLayout(self.Noteslay)
        self.Buttons = QtGui.QHBoxLayout()
        self.Buttons.setObjectName("Buttons")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Buttons.addItem(spacerItem)
        self.Add = QtGui.QPushButton(self.centralwidget)
        self.Add.setObjectName("Add")
        self.Buttons.addWidget(self.Add)
        self.Cancel = QtGui.QPushButton(self.centralwidget)
        self.Cancel.setObjectName("Cancel")
        self.Buttons.addWidget(self.Cancel)
        self.verticalLayout.addLayout(self.Buttons)
        AddDive.setCentralWidget(self.centralwidget)

        self.retranslateUi(AddDive)
        QtCore.QMetaObject.connectSlotsByName(AddDive)

    def retranslateUi(self, AddDive):
        AddDive.setWindowTitle(QtGui.QApplication.translate("AddDive", "Add a Dive", None, QtGui.QApplication.UnicodeUTF8))
        self.LNumber.setText(QtGui.QApplication.translate("AddDive", "Dive Number", None, QtGui.QApplication.UnicodeUTF8))
        self.LLocation.setText(QtGui.QApplication.translate("AddDive", "Location        ", None, QtGui.QApplication.UnicodeUTF8))
        self.LDate.setText(QtGui.QApplication.translate("AddDive", "Dive Date", None, QtGui.QApplication.UnicodeUTF8))
        self.IDate.setDisplayFormat(QtGui.QApplication.translate("AddDive", "yyyy-MM-dd", None, QtGui.QApplication.UnicodeUTF8))
        self.LFormatDate.setText(QtGui.QApplication.translate("AddDive", "(Year-Month-Day)", None, QtGui.QApplication.UnicodeUTF8))
        self.LTimeIn.setText(QtGui.QApplication.translate("AddDive", "Time In", None, QtGui.QApplication.UnicodeUTF8))
        self.ITimeIn.setDisplayFormat(QtGui.QApplication.translate("AddDive", "HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LTimeOut.setText(QtGui.QApplication.translate("AddDive", "Time Out", None, QtGui.QApplication.UnicodeUTF8))
        self.ITimeOut.setDisplayFormat(QtGui.QApplication.translate("AddDive", "HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LBarIn.setText(QtGui.QApplication.translate("AddDive", "Bar In", None, QtGui.QApplication.UnicodeUTF8))
        self.LBarOut.setText(QtGui.QApplication.translate("AddDive", "Bar Out", None, QtGui.QApplication.UnicodeUTF8))
        self.Ltemperature.setText(QtGui.QApplication.translate("AddDive", "Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.LSight.setText(QtGui.QApplication.translate("AddDive", "Sight", None, QtGui.QApplication.UnicodeUTF8))
        self.LLead.setText(QtGui.QApplication.translate("AddDive", "Lead", None, QtGui.QApplication.UnicodeUTF8))
        self.Ldepth.setText(QtGui.QApplication.translate("AddDive", "Depth", None, QtGui.QApplication.UnicodeUTF8))
        self.LTime.setText(QtGui.QApplication.translate("AddDive", "Dive Time", None, QtGui.QApplication.UnicodeUTF8))
        self.LFormatTime.setText(QtGui.QApplication.translate("AddDive", "In minutes, When time in/out is filled in not needed", None, QtGui.QApplication.UnicodeUTF8))
        self.LNotes.setText(QtGui.QApplication.translate("AddDive", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.Add.setText(QtGui.QApplication.translate("AddDive", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.Cancel.setText(QtGui.QApplication.translate("AddDive", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

