# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/editNew.ui'
#
# Created: Mon Aug 16 16:49:11 2010
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_EditDive(object):
    def setupUi(self, EditDive):
        EditDive.setObjectName("EditDive")
        EditDive.resize(539, 634)
        self.centralwidget = QtGui.QWidget(EditDive)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.LNumber = QtGui.QLabel(self.centralwidget)
        self.LNumber.setObjectName("LNumber")
        self.gridLayout.addWidget(self.LNumber, 0, 0, 1, 3)
        self.INumber = QtGui.QLineEdit(self.centralwidget)
        self.INumber.setObjectName("INumber")
        self.gridLayout.addWidget(self.INumber, 0, 3, 1, 1)
        self.LDate = QtGui.QLabel(self.centralwidget)
        self.LDate.setObjectName("LDate")
        self.gridLayout.addWidget(self.LDate, 1, 0, 1, 3)
        self.IDate = QtGui.QDateEdit(self.centralwidget)
        self.IDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2010, 8, 14), QtCore.QTime(0, 0, 0)))
        self.IDate.setCalendarPopup(True)
        self.IDate.setCurrentSectionIndex(0)
        self.IDate.setTimeSpec(QtCore.Qt.LocalTime)
        self.IDate.setDate(QtCore.QDate(2010, 8, 14))
        self.IDate.setObjectName("IDate")
        self.gridLayout.addWidget(self.IDate, 1, 3, 1, 1)
        self.LLocation = QtGui.QLabel(self.centralwidget)
        self.LLocation.setObjectName("LLocation")
        self.gridLayout.addWidget(self.LLocation, 2, 0, 1, 3)
        self.ILocation = QtGui.QLineEdit(self.centralwidget)
        self.ILocation.setObjectName("ILocation")
        self.gridLayout.addWidget(self.ILocation, 2, 3, 1, 1)
        self.LDepth = QtGui.QLabel(self.centralwidget)
        self.LDepth.setObjectName("LDepth")
        self.gridLayout.addWidget(self.LDepth, 3, 0, 1, 3)
        self.IDepth = QtGui.QLineEdit(self.centralwidget)
        self.IDepth.setObjectName("IDepth")
        self.gridLayout.addWidget(self.IDepth, 3, 3, 1, 1)
        self.LTimeIn = QtGui.QLabel(self.centralwidget)
        self.LTimeIn.setObjectName("LTimeIn")
        self.gridLayout.addWidget(self.LTimeIn, 4, 0, 1, 3)
        self.ITimeIn = QtGui.QTimeEdit(self.centralwidget)
        self.ITimeIn.setCalendarPopup(True)
        self.ITimeIn.setObjectName("ITimeIn")
        self.gridLayout.addWidget(self.ITimeIn, 4, 3, 1, 1)
        self.LTimeOut = QtGui.QLabel(self.centralwidget)
        self.LTimeOut.setObjectName("LTimeOut")
        self.gridLayout.addWidget(self.LTimeOut, 5, 0, 1, 3)
        self.ITimeOut = QtGui.QTimeEdit(self.centralwidget)
        self.ITimeOut.setCalendarPopup(True)
        self.ITimeOut.setObjectName("ITimeOut")
        self.gridLayout.addWidget(self.ITimeOut, 5, 3, 1, 1)
        self.LTime = QtGui.QLabel(self.centralwidget)
        self.LTime.setObjectName("LTime")
        self.gridLayout.addWidget(self.LTime, 6, 0, 1, 3)
        self.ITime = QtGui.QLineEdit(self.centralwidget)
        self.ITime.setObjectName("ITime")
        self.gridLayout.addWidget(self.ITime, 6, 3, 1, 1)
        self.LLead = QtGui.QLabel(self.centralwidget)
        self.LLead.setObjectName("LLead")
        self.gridLayout.addWidget(self.LLead, 7, 0, 1, 3)
        self.ILead = QtGui.QSpinBox(self.centralwidget)
        self.ILead.setObjectName("ILead")
        self.gridLayout.addWidget(self.ILead, 7, 3, 1, 1)
        self.LSight = QtGui.QLabel(self.centralwidget)
        self.LSight.setObjectName("LSight")
        self.gridLayout.addWidget(self.LSight, 8, 0, 1, 3)
        self.ISight = QtGui.QSpinBox(self.centralwidget)
        self.ISight.setObjectName("ISight")
        self.gridLayout.addWidget(self.ISight, 8, 3, 1, 1)
        self.LTemperature = QtGui.QLabel(self.centralwidget)
        self.LTemperature.setObjectName("LTemperature")
        self.gridLayout.addWidget(self.LTemperature, 9, 0, 1, 3)
        self.ITemperature = QtGui.QLineEdit(self.centralwidget)
        self.ITemperature.setObjectName("ITemperature")
        self.gridLayout.addWidget(self.ITemperature, 9, 3, 1, 1)
        self.LBarIn = QtGui.QLabel(self.centralwidget)
        self.LBarIn.setObjectName("LBarIn")
        self.gridLayout.addWidget(self.LBarIn, 10, 0, 1, 1)
        self.IBarIn = QtGui.QLineEdit(self.centralwidget)
        self.IBarIn.setObjectName("IBarIn")
        self.gridLayout.addWidget(self.IBarIn, 10, 1, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 10, 2, 1, 1)
        self.IBarOut = QtGui.QLineEdit(self.centralwidget)
        self.IBarOut.setObjectName("IBarOut")
        self.gridLayout.addWidget(self.IBarOut, 10, 3, 1, 1)
        self.LNotes = QtGui.QLabel(self.centralwidget)
        self.LNotes.setObjectName("LNotes")
        self.gridLayout.addWidget(self.LNotes, 11, 0, 1, 3)
        self.INotes = QtGui.QTextEdit(self.centralwidget)
        self.INotes.setObjectName("INotes")
        self.gridLayout.addWidget(self.INotes, 11, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Edit = QtGui.QPushButton(self.centralwidget)
        self.Edit.setObjectName("Edit")
        self.horizontalLayout.addWidget(self.Edit)
        self.Cancel = QtGui.QPushButton(self.centralwidget)
        self.Cancel.setObjectName("Cancel")
        self.horizontalLayout.addWidget(self.Cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        EditDive.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(EditDive)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 539, 25))
        self.menubar.setObjectName("menubar")
        EditDive.setMenuBar(self.menubar)

        self.retranslateUi(EditDive)
        QtCore.QMetaObject.connectSlotsByName(EditDive)

    def retranslateUi(self, EditDive):
        EditDive.setWindowTitle(QtGui.QApplication.translate("EditDive", "Edit a Dive", None, QtGui.QApplication.UnicodeUTF8))
        self.LNumber.setText(QtGui.QApplication.translate("EditDive", "Dive Number", None, QtGui.QApplication.UnicodeUTF8))
        self.LDate.setText(QtGui.QApplication.translate("EditDive", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.IDate.setDisplayFormat(QtGui.QApplication.translate("EditDive", "dd-MM-yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.LLocation.setText(QtGui.QApplication.translate("EditDive", "Location", None, QtGui.QApplication.UnicodeUTF8))
        self.LDepth.setText(QtGui.QApplication.translate("EditDive", "Depth", None, QtGui.QApplication.UnicodeUTF8))
        self.LTimeIn.setText(QtGui.QApplication.translate("EditDive", "Time In", None, QtGui.QApplication.UnicodeUTF8))
        self.ITimeIn.setDisplayFormat(QtGui.QApplication.translate("EditDive", "hh:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LTimeOut.setText(QtGui.QApplication.translate("EditDive", "Time Out", None, QtGui.QApplication.UnicodeUTF8))
        self.ITimeOut.setDisplayFormat(QtGui.QApplication.translate("EditDive", "hh:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LTime.setText(QtGui.QApplication.translate("EditDive", "Dive Time", None, QtGui.QApplication.UnicodeUTF8))
        self.LLead.setText(QtGui.QApplication.translate("EditDive", "Lead", None, QtGui.QApplication.UnicodeUTF8))
        self.LSight.setText(QtGui.QApplication.translate("EditDive", "Sight", None, QtGui.QApplication.UnicodeUTF8))
        self.LTemperature.setText(QtGui.QApplication.translate("EditDive", "Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.LBarIn.setText(QtGui.QApplication.translate("EditDive", "Bar In", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("EditDive", "Bar Out", None, QtGui.QApplication.UnicodeUTF8))
        self.LNotes.setText(QtGui.QApplication.translate("EditDive", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.Edit.setText(QtGui.QApplication.translate("EditDive", "Edit Dive", None, QtGui.QApplication.UnicodeUTF8))
        self.Cancel.setText(QtGui.QApplication.translate("EditDive", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

