# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/edit.ui'
#
# Created: Sun Aug 15 13:04:25 2010
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_EditDive(object):
    def setupUi(self, EditDive):
        EditDive.setObjectName("EditDive")
        EditDive.resize(657, 571)
        EditDive.setMinimumSize(QtCore.QSize(657, 571))
        EditDive.setMaximumSize(QtCore.QSize(657, 571))
        EditDive.setSizeIncrement(QtCore.QSize(657, 571))
        EditDive.setBaseSize(QtCore.QSize(657, 571))
        self.LNumber = QtGui.QLabel(EditDive)
        self.LNumber.setGeometry(QtCore.QRect(20, 20, 171, 18))
        self.LNumber.setObjectName("LNumber")
        self.INumber = QtGui.QLineEdit(EditDive)
        self.INumber.setGeometry(QtCore.QRect(250, 20, 81, 24))
        self.INumber.setObjectName("INumber")
        self.IDepth = QtGui.QLineEdit(EditDive)
        self.IDepth.setGeometry(QtCore.QRect(250, 110, 81, 24))
        self.IDepth.setObjectName("IDepth")
        self.ITemperature = QtGui.QLineEdit(EditDive)
        self.ITemperature.setGeometry(QtCore.QRect(250, 290, 81, 24))
        self.ITemperature.setObjectName("ITemperature")
        self.INotes = QtGui.QTextEdit(EditDive)
        self.INotes.setGeometry(QtCore.QRect(250, 320, 401, 191))
        self.INotes.setObjectName("INotes")
        self.LTime = QtGui.QLabel(EditDive)
        self.LTime.setGeometry(QtCore.QRect(20, 200, 171, 18))
        self.LTime.setObjectName("LTime")
        self.IDate = QtGui.QDateEdit(EditDive)
        self.IDate.setGeometry(QtCore.QRect(250, 50, 110, 26))
        self.IDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2010, 8, 14), QtCore.QTime(0, 0, 0)))
        self.IDate.setCalendarPopup(True)
        self.IDate.setCurrentSectionIndex(0)
        self.IDate.setTimeSpec(QtCore.Qt.LocalTime)
        self.IDate.setDate(QtCore.QDate(2010, 8, 14))
        self.IDate.setObjectName("IDate")
        self.LTemperature = QtGui.QLabel(EditDive)
        self.LTemperature.setGeometry(QtCore.QRect(20, 290, 171, 18))
        self.LTemperature.setObjectName("LTemperature")
        self.Edit = QtGui.QPushButton(EditDive)
        self.Edit.setGeometry(QtCore.QRect(20, 520, 90, 27))
        self.Edit.setObjectName("Edit")
        self.ITimeIn = QtGui.QTimeEdit(EditDive)
        self.ITimeIn.setGeometry(QtCore.QRect(250, 140, 118, 26))
        self.ITimeIn.setCalendarPopup(True)
        self.ITimeIn.setObjectName("ITimeIn")
        self.LDate = QtGui.QLabel(EditDive)
        self.LDate.setGeometry(QtCore.QRect(20, 50, 171, 18))
        self.LDate.setObjectName("LDate")
        self.ITime = QtGui.QLineEdit(EditDive)
        self.ITime.setGeometry(QtCore.QRect(250, 200, 81, 24))
        self.ITime.setObjectName("ITime")
        self.LLead = QtGui.QLabel(EditDive)
        self.LLead.setGeometry(QtCore.QRect(20, 230, 171, 18))
        self.LLead.setObjectName("LLead")
        self.LTimeOut = QtGui.QLabel(EditDive)
        self.LTimeOut.setGeometry(QtCore.QRect(20, 170, 171, 18))
        self.LTimeOut.setObjectName("LTimeOut")
        self.Cancel = QtGui.QPushButton(EditDive)
        self.Cancel.setGeometry(QtCore.QRect(130, 520, 90, 27))
        self.Cancel.setObjectName("Cancel")
        self.LNotes = QtGui.QLabel(EditDive)
        self.LNotes.setGeometry(QtCore.QRect(20, 320, 171, 18))
        self.LNotes.setObjectName("LNotes")
        self.LDepth = QtGui.QLabel(EditDive)
        self.LDepth.setGeometry(QtCore.QRect(20, 110, 171, 18))
        self.LDepth.setObjectName("LDepth")
        self.LTimeIn = QtGui.QLabel(EditDive)
        self.LTimeIn.setGeometry(QtCore.QRect(20, 140, 171, 18))
        self.LTimeIn.setObjectName("LTimeIn")
        self.ILocation = QtGui.QLineEdit(EditDive)
        self.ILocation.setGeometry(QtCore.QRect(250, 80, 301, 24))
        self.ILocation.setObjectName("ILocation")
        self.ISight = QtGui.QSpinBox(EditDive)
        self.ISight.setGeometry(QtCore.QRect(250, 260, 50, 26))
        self.ISight.setObjectName("ISight")
        self.ILead = QtGui.QSpinBox(EditDive)
        self.ILead.setGeometry(QtCore.QRect(250, 230, 50, 26))
        self.ILead.setObjectName("ILead")
        self.LLocation = QtGui.QLabel(EditDive)
        self.LLocation.setGeometry(QtCore.QRect(20, 80, 171, 18))
        self.LLocation.setObjectName("LLocation")
        self.ITimeOut = QtGui.QTimeEdit(EditDive)
        self.ITimeOut.setGeometry(QtCore.QRect(250, 170, 118, 26))
        self.ITimeOut.setCalendarPopup(True)
        self.ITimeOut.setObjectName("ITimeOut")
        self.LSight = QtGui.QLabel(EditDive)
        self.LSight.setGeometry(QtCore.QRect(20, 260, 171, 18))
        self.LSight.setObjectName("LSight")

        self.retranslateUi(EditDive)
        QtCore.QMetaObject.connectSlotsByName(EditDive)
        EditDive.setTabOrder(self.INumber, self.IDate)
        EditDive.setTabOrder(self.IDate, self.ILocation)
        EditDive.setTabOrder(self.ILocation, self.IDepth)
        EditDive.setTabOrder(self.IDepth, self.ITimeIn)
        EditDive.setTabOrder(self.ITimeIn, self.ITimeOut)
        EditDive.setTabOrder(self.ITimeOut, self.ITime)
        EditDive.setTabOrder(self.ITime, self.ILead)
        EditDive.setTabOrder(self.ILead, self.ISight)
        EditDive.setTabOrder(self.ISight, self.ITemperature)
        EditDive.setTabOrder(self.ITemperature, self.INotes)
        EditDive.setTabOrder(self.INotes, self.Edit)
        EditDive.setTabOrder(self.Edit, self.Cancel)

    def retranslateUi(self, EditDive):
        EditDive.setWindowTitle(QtGui.QApplication.translate("EditDive", "Edit Dive", None, QtGui.QApplication.UnicodeUTF8))
        self.LNumber.setText(QtGui.QApplication.translate("EditDive", "Dive Number", None, QtGui.QApplication.UnicodeUTF8))
        self.LTime.setText(QtGui.QApplication.translate("EditDive", "Dive Time", None, QtGui.QApplication.UnicodeUTF8))
        self.IDate.setDisplayFormat(QtGui.QApplication.translate("EditDive", "dd-MM-yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.LTemperature.setText(QtGui.QApplication.translate("EditDive", "Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.Edit.setText(QtGui.QApplication.translate("EditDive", "Edit Dive", None, QtGui.QApplication.UnicodeUTF8))
        self.ITimeIn.setDisplayFormat(QtGui.QApplication.translate("EditDive", "hh:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LDate.setText(QtGui.QApplication.translate("EditDive", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.LLead.setText(QtGui.QApplication.translate("EditDive", "Lead", None, QtGui.QApplication.UnicodeUTF8))
        self.LTimeOut.setText(QtGui.QApplication.translate("EditDive", "Time Out", None, QtGui.QApplication.UnicodeUTF8))
        self.Cancel.setText(QtGui.QApplication.translate("EditDive", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.LNotes.setText(QtGui.QApplication.translate("EditDive", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.LDepth.setText(QtGui.QApplication.translate("EditDive", "Depth", None, QtGui.QApplication.UnicodeUTF8))
        self.LTimeIn.setText(QtGui.QApplication.translate("EditDive", "Time In", None, QtGui.QApplication.UnicodeUTF8))
        self.LLocation.setText(QtGui.QApplication.translate("EditDive", "Location", None, QtGui.QApplication.UnicodeUTF8))
        self.ITimeOut.setDisplayFormat(QtGui.QApplication.translate("EditDive", "hh:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.LSight.setText(QtGui.QApplication.translate("EditDive", "Sight", None, QtGui.QApplication.UnicodeUTF8))

