# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/stats.ui'
#
# Created: Wed Aug 18 17:21:08 2010
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Stats(object):
    def setupUi(self, Stats):
        Stats.setObjectName("Stats")
        Stats.resize(352, 326)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Stats.sizePolicy().hasHeightForWidth())
        Stats.setSizePolicy(sizePolicy)
        Stats.setMinimumSize(QtCore.QSize(352, 326))
        Stats.setMaximumSize(QtCore.QSize(352, 326))
        Stats.setBaseSize(QtCore.QSize(352, 326))
        self.centralwidget = QtGui.QWidget(Stats)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TopLay = QtGui.QHBoxLayout()
        self.TopLay.setObjectName("TopLay")
        self.LogoFrame = QtGui.QFrame(self.centralwidget)
        self.LogoFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.LogoFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.LogoFrame.setObjectName("LogoFrame")
        self.Logo = QtGui.QGraphicsView(self.LogoFrame)
        self.Logo.setGeometry(QtCore.QRect(0, 0, 64, 64))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Logo.sizePolicy().hasHeightForWidth())
        self.Logo.setSizePolicy(sizePolicy)
        self.Logo.setMinimumSize(QtCore.QSize(64, 64))
        self.Logo.setMaximumSize(QtCore.QSize(64, 64))
        self.Logo.setBaseSize(QtCore.QSize(64, 64))
        self.Logo.setStyleSheet("background-image: url(:/img/icon.png);")
        self.Logo.setFrameShape(QtGui.QFrame.NoFrame)
        self.Logo.setObjectName("Logo")
        self.TopLay.addWidget(self.LogoFrame)
        self.Title = QtGui.QLabel(self.centralwidget)
        self.Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Title.setObjectName("Title")
        self.TopLay.addWidget(self.Title)
        self.verticalLayout.addLayout(self.TopLay)
        self.Statslay = QtGui.QGridLayout()
        self.Statslay.setObjectName("Statslay")
        self.LTotalDives = QtGui.QLabel(self.centralwidget)
        self.LTotalDives.setObjectName("LTotalDives")
        self.Statslay.addWidget(self.LTotalDives, 0, 0, 1, 1)
        self.ITotalDives = QtGui.QLabel(self.centralwidget)
        self.ITotalDives.setObjectName("ITotalDives")
        self.Statslay.addWidget(self.ITotalDives, 0, 1, 1, 1)
        self.LAvgAir = QtGui.QLabel(self.centralwidget)
        self.LAvgAir.setObjectName("LAvgAir")
        self.Statslay.addWidget(self.LAvgAir, 1, 0, 1, 1)
        self.IAvgAir = QtGui.QLabel(self.centralwidget)
        self.IAvgAir.setObjectName("IAvgAir")
        self.Statslay.addWidget(self.IAvgAir, 1, 1, 1, 1)
        self.LAvgTime = QtGui.QLabel(self.centralwidget)
        self.LAvgTime.setObjectName("LAvgTime")
        self.Statslay.addWidget(self.LAvgTime, 2, 0, 1, 1)
        self.IAvgTime = QtGui.QLabel(self.centralwidget)
        self.IAvgTime.setObjectName("IAvgTime")
        self.Statslay.addWidget(self.IAvgTime, 2, 1, 1, 1)
        self.LTotalTime = QtGui.QLabel(self.centralwidget)
        self.LTotalTime.setObjectName("LTotalTime")
        self.Statslay.addWidget(self.LTotalTime, 3, 0, 1, 1)
        self.ITotalTime = QtGui.QLabel(self.centralwidget)
        self.ITotalTime.setObjectName("ITotalTime")
        self.Statslay.addWidget(self.ITotalTime, 3, 1, 1, 1)
        self.LTotalLocations = QtGui.QLabel(self.centralwidget)
        self.LTotalLocations.setObjectName("LTotalLocations")
        self.Statslay.addWidget(self.LTotalLocations, 4, 0, 1, 1)
        self.ITotalLocations = QtGui.QLabel(self.centralwidget)
        self.ITotalLocations.setObjectName("ITotalLocations")
        self.Statslay.addWidget(self.ITotalLocations, 4, 1, 1, 1)
        self.LMaxDepth = QtGui.QLabel(self.centralwidget)
        self.LMaxDepth.setObjectName("LMaxDepth")
        self.Statslay.addWidget(self.LMaxDepth, 5, 0, 1, 1)
        self.IMaxDepth = QtGui.QLabel(self.centralwidget)
        self.IMaxDepth.setObjectName("IMaxDepth")
        self.Statslay.addWidget(self.IMaxDepth, 5, 1, 1, 1)
        self.LAvgDepth = QtGui.QLabel(self.centralwidget)
        self.LAvgDepth.setObjectName("LAvgDepth")
        self.Statslay.addWidget(self.LAvgDepth, 6, 0, 1, 1)
        self.IAvgDepth = QtGui.QLabel(self.centralwidget)
        self.IAvgDepth.setObjectName("IAvgDepth")
        self.Statslay.addWidget(self.IAvgDepth, 6, 1, 1, 1)
        self.verticalLayout.addLayout(self.Statslay)
        self.ButtonsLay = QtGui.QHBoxLayout()
        self.ButtonsLay.setObjectName("ButtonsLay")
        self.Ok = QtGui.QPushButton(self.centralwidget)
        self.Ok.setObjectName("Ok")
        self.ButtonsLay.addWidget(self.Ok)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.ButtonsLay.addItem(spacerItem)
        self.verticalLayout.addLayout(self.ButtonsLay)
        Stats.setCentralWidget(self.centralwidget)

        self.retranslateUi(Stats)
        QtCore.QMetaObject.connectSlotsByName(Stats)

    def retranslateUi(self, Stats):
        Stats.setWindowTitle(QtGui.QApplication.translate("Stats", "My Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.Title.setText(QtGui.QApplication.translate("Stats", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:600;\">Your Statistics</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.LTotalDives.setText(QtGui.QApplication.translate("Stats", "Total dives", None, QtGui.QApplication.UnicodeUTF8))
        self.ITotalDives.setText(QtGui.QApplication.translate("Stats", "*TotalDives*", None, QtGui.QApplication.UnicodeUTF8))
        self.LAvgAir.setText(QtGui.QApplication.translate("Stats", "Average air usage", None, QtGui.QApplication.UnicodeUTF8))
        self.IAvgAir.setText(QtGui.QApplication.translate("Stats", "*Average air usage*", None, QtGui.QApplication.UnicodeUTF8))
        self.LAvgTime.setText(QtGui.QApplication.translate("Stats", "Average dive time", None, QtGui.QApplication.UnicodeUTF8))
        self.IAvgTime.setText(QtGui.QApplication.translate("Stats", "*Average dive time*", None, QtGui.QApplication.UnicodeUTF8))
        self.LTotalTime.setText(QtGui.QApplication.translate("Stats", "Total dive time", None, QtGui.QApplication.UnicodeUTF8))
        self.ITotalTime.setText(QtGui.QApplication.translate("Stats", "*TotalDiveTime*", None, QtGui.QApplication.UnicodeUTF8))
        self.LTotalLocations.setText(QtGui.QApplication.translate("Stats", "Total locations", None, QtGui.QApplication.UnicodeUTF8))
        self.ITotalLocations.setText(QtGui.QApplication.translate("Stats", "*TotalLocations*", None, QtGui.QApplication.UnicodeUTF8))
        self.LMaxDepth.setText(QtGui.QApplication.translate("Stats", "Maximum depth", None, QtGui.QApplication.UnicodeUTF8))
        self.IMaxDepth.setText(QtGui.QApplication.translate("Stats", "*MaxDepth*", None, QtGui.QApplication.UnicodeUTF8))
        self.LAvgDepth.setText(QtGui.QApplication.translate("Stats", "Average depth", None, QtGui.QApplication.UnicodeUTF8))
        self.IAvgDepth.setText(QtGui.QApplication.translate("Stats", "*Average Depth*", None, QtGui.QApplication.UnicodeUTF8))
        self.Ok.setText(QtGui.QApplication.translate("Stats", "Ok, Thanks", None, QtGui.QApplication.UnicodeUTF8))

import res_rc
