# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/window.ui'
#
# Created: Mon Aug 16 16:38:23 2010
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Logbook(object):
    def setupUi(self, Logbook):
        Logbook.setObjectName("Logbook")
        Logbook.resize(984, 606)
        Logbook.setMinimumSize(QtCore.QSize(984, 606))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Logbook.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(Logbook)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Left = QtGui.QHBoxLayout()
        self.Left.setSpacing(0)
        self.Left.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.Left.setContentsMargins(-1, -1, 5, -1)
        self.Left.setObjectName("Left")
        self.ListDives = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListDives.sizePolicy().hasHeightForWidth())
        self.ListDives.setSizePolicy(sizePolicy)
        self.ListDives.setMaximumSize(QtCore.QSize(350, 16777215))
        self.ListDives.setBaseSize(QtCore.QSize(350, 0))
        self.ListDives.setObjectName("ListDives")
        self.Left.addWidget(self.ListDives)
        self.gridLayout.addLayout(self.Left, 0, 0, 2, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Planner = QtGui.QGraphicsView(self.frame)
        self.Planner.setGeometry(QtCore.QRect(0, 0, 200, 200))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Planner.sizePolicy().hasHeightForWidth())
        self.Planner.setSizePolicy(sizePolicy)
        self.Planner.setMinimumSize(QtCore.QSize(200, 200))
        self.Planner.setMaximumSize(QtCore.QSize(200, 200))
        self.Planner.setBaseSize(QtCore.QSize(200, 200))
        self.Planner.setStyleSheet("background-image: url(:/img/log.png);")
        self.Planner.setObjectName("Planner")
        self.IDepth = QtGui.QLabel(self.frame)
        self.IDepth.setGeometry(QtCore.QRect(10, 90, 62, 18))
        self.IDepth.setObjectName("IDepth")
        self.ITime = QtGui.QLabel(self.frame)
        self.ITime.setGeometry(QtCore.QRect(80, 130, 62, 18))
        self.ITime.setObjectName("ITime")
        self.horizontalLayout.addWidget(self.frame)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.LNumber = QtGui.QLabel(self.centralwidget)
        self.LNumber.setObjectName("LNumber")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.LNumber)
        self.INumber = QtGui.QLabel(self.centralwidget)
        self.INumber.setObjectName("INumber")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.INumber)
        self.LDate = QtGui.QLabel(self.centralwidget)
        self.LDate.setObjectName("LDate")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.LDate)
        self.IDate = QtGui.QLabel(self.centralwidget)
        self.IDate.setObjectName("IDate")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.IDate)
        self.LLocation = QtGui.QLabel(self.centralwidget)
        self.LLocation.setObjectName("LLocation")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.LLocation)
        self.ILocation = QtGui.QLabel(self.centralwidget)
        self.ILocation.setObjectName("ILocation")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.ILocation)
        self.LTimeIn = QtGui.QLabel(self.centralwidget)
        self.LTimeIn.setObjectName("LTimeIn")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.LTimeIn)
        self.ITimeIn = QtGui.QLabel(self.centralwidget)
        self.ITimeIn.setObjectName("ITimeIn")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.ITimeIn)
        self.LTimeOut = QtGui.QLabel(self.centralwidget)
        self.LTimeOut.setObjectName("LTimeOut")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.LTimeOut)
        self.ITimeOut = QtGui.QLabel(self.centralwidget)
        self.ITimeOut.setObjectName("ITimeOut")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.ITimeOut)
        self.LSight = QtGui.QLabel(self.centralwidget)
        self.LSight.setObjectName("LSight")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.LSight)
        self.ISight = QtGui.QLabel(self.centralwidget)
        self.ISight.setObjectName("ISight")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.ISight)
        self.LLead = QtGui.QLabel(self.centralwidget)
        self.LLead.setObjectName("LLead")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.LLead)
        self.ILead = QtGui.QLabel(self.centralwidget)
        self.ILead.setObjectName("ILead")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.ILead)
        self.LTemperature = QtGui.QLabel(self.centralwidget)
        self.LTemperature.setObjectName("LTemperature")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.LTemperature)
        self.ITemperature = QtGui.QLabel(self.centralwidget)
        self.ITemperature.setObjectName("ITemperature")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.ITemperature)
        self.LBarIn = QtGui.QLabel(self.centralwidget)
        self.LBarIn.setObjectName("LBarIn")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.LBarIn)
        self.IBarIn = QtGui.QLabel(self.centralwidget)
        self.IBarIn.setObjectName("IBarIn")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.IBarIn)
        self.LBarOut = QtGui.QLabel(self.centralwidget)
        self.LBarOut.setObjectName("LBarOut")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.LBarOut)
        self.IBarOut = QtGui.QLabel(self.centralwidget)
        self.IBarOut.setObjectName("IBarOut")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.IBarOut)
        self.horizontalLayout.addLayout(self.formLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Buttons = QtGui.QHBoxLayout()
        self.Buttons.setObjectName("Buttons")
        self.Delete = QtGui.QPushButton(self.centralwidget)
        self.Delete.setObjectName("Delete")
        self.Buttons.addWidget(self.Delete)
        self.Edit = QtGui.QPushButton(self.centralwidget)
        self.Edit.setObjectName("Edit")
        self.Buttons.addWidget(self.Edit)
        self.verticalLayout.addLayout(self.Buttons)
        self.INotes = QtGui.QTextBrowser(self.centralwidget)
        self.INotes.setObjectName("INotes")
        self.verticalLayout.addWidget(self.INotes)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 1)
        Logbook.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Logbook)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 984, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Logbook.setMenuBar(self.menubar)
        self.AddDive = QtGui.QAction(Logbook)
        self.AddDive.setObjectName("AddDive")
        self.Stats = QtGui.QAction(Logbook)
        self.Stats.setObjectName("Stats")
        self.Quit = QtGui.QAction(Logbook)
        self.Quit.setObjectName("Quit")
        self.About = QtGui.QAction(Logbook)
        self.About.setObjectName("About")
        self.License = QtGui.QAction(Logbook)
        self.License.setObjectName("License")
        self.menuFile.addAction(self.AddDive)
        self.menuFile.addAction(self.Stats)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.Quit)
        self.menuHelp.addAction(self.About)
        self.menuHelp.addAction(self.License)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Logbook)
        QtCore.QMetaObject.connectSlotsByName(Logbook)

    def retranslateUi(self, Logbook):
        Logbook.setWindowTitle(QtGui.QApplication.translate("Logbook", "Logbook", None, QtGui.QApplication.UnicodeUTF8))
        self.IDepth.setText(QtGui.QApplication.translate("Logbook", "*depth*", None, QtGui.QApplication.UnicodeUTF8))
        self.ITime.setText(QtGui.QApplication.translate("Logbook", "*Time*", None, QtGui.QApplication.UnicodeUTF8))
        self.LNumber.setText(QtGui.QApplication.translate("Logbook", "Dive Number", None, QtGui.QApplication.UnicodeUTF8))
        self.INumber.setText(QtGui.QApplication.translate("Logbook", "*RealNumber*", None, QtGui.QApplication.UnicodeUTF8))
        self.LDate.setText(QtGui.QApplication.translate("Logbook", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.IDate.setText(QtGui.QApplication.translate("Logbook", "*RealDate*", None, QtGui.QApplication.UnicodeUTF8))
        self.LLocation.setText(QtGui.QApplication.translate("Logbook", "Location", None, QtGui.QApplication.UnicodeUTF8))
        self.ILocation.setText(QtGui.QApplication.translate("Logbook", "*RealLocation*", None, QtGui.QApplication.UnicodeUTF8))
        self.LTimeIn.setText(QtGui.QApplication.translate("Logbook", "Time In", None, QtGui.QApplication.UnicodeUTF8))
        self.ITimeIn.setText(QtGui.QApplication.translate("Logbook", "*RealTimeIn*", None, QtGui.QApplication.UnicodeUTF8))
        self.LTimeOut.setText(QtGui.QApplication.translate("Logbook", "Time Out", None, QtGui.QApplication.UnicodeUTF8))
        self.ITimeOut.setText(QtGui.QApplication.translate("Logbook", "*RealTimeOut*", None, QtGui.QApplication.UnicodeUTF8))
        self.LSight.setText(QtGui.QApplication.translate("Logbook", "Sight", None, QtGui.QApplication.UnicodeUTF8))
        self.ISight.setText(QtGui.QApplication.translate("Logbook", "*RealSight*", None, QtGui.QApplication.UnicodeUTF8))
        self.LLead.setText(QtGui.QApplication.translate("Logbook", "Lead", None, QtGui.QApplication.UnicodeUTF8))
        self.ILead.setText(QtGui.QApplication.translate("Logbook", "*RealLead*", None, QtGui.QApplication.UnicodeUTF8))
        self.LTemperature.setText(QtGui.QApplication.translate("Logbook", "Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.ITemperature.setText(QtGui.QApplication.translate("Logbook", "*RealTemperature*", None, QtGui.QApplication.UnicodeUTF8))
        self.LBarIn.setText(QtGui.QApplication.translate("Logbook", "Bar In", None, QtGui.QApplication.UnicodeUTF8))
        self.IBarIn.setText(QtGui.QApplication.translate("Logbook", "*RealBarIn*", None, QtGui.QApplication.UnicodeUTF8))
        self.LBarOut.setText(QtGui.QApplication.translate("Logbook", "Bar Out", None, QtGui.QApplication.UnicodeUTF8))
        self.IBarOut.setText(QtGui.QApplication.translate("Logbook", "*RealBarOut*", None, QtGui.QApplication.UnicodeUTF8))
        self.Delete.setText(QtGui.QApplication.translate("Logbook", "Delete Dive", None, QtGui.QApplication.UnicodeUTF8))
        self.Edit.setText(QtGui.QApplication.translate("Logbook", "Edit Dive", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("Logbook", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("Logbook", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.AddDive.setText(QtGui.QApplication.translate("Logbook", "Add Dive", None, QtGui.QApplication.UnicodeUTF8))
        self.Stats.setText(QtGui.QApplication.translate("Logbook", "View Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.Quit.setText(QtGui.QApplication.translate("Logbook", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.About.setText(QtGui.QApplication.translate("Logbook", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.License.setText(QtGui.QApplication.translate("Logbook", "License", None, QtGui.QApplication.UnicodeUTF8))

import res_rc
