# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/window.ui'
#
# Created: Thu Aug 19 16:41:19 2010
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dive(object):
    def setupUi(self, Dive):
        Dive.setObjectName("Dive")
        Dive.resize(819, 598)
        Dive.setMinimumSize(QtCore.QSize(761, 495))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dive.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(Dive)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ListDives = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListDives.sizePolicy().hasHeightForWidth())
        self.ListDives.setSizePolicy(sizePolicy)
        self.ListDives.setMinimumSize(QtCore.QSize(250, 0))
        self.ListDives.setMaximumSize(QtCore.QSize(250, 16777215))
        self.ListDives.setBaseSize(QtCore.QSize(250, 0))
        self.ListDives.setObjectName("ListDives")
        self.horizontalLayout.addWidget(self.ListDives)
        self.Right = QtGui.QVBoxLayout()
        self.Right.setObjectName("Right")
        self.Top = QtGui.QHBoxLayout()
        self.Top.setObjectName("Top")
        self.GraphFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GraphFrame.sizePolicy().hasHeightForWidth())
        self.GraphFrame.setSizePolicy(sizePolicy)
        self.GraphFrame.setMinimumSize(QtCore.QSize(200, 200))
        self.GraphFrame.setMaximumSize(QtCore.QSize(200, 200))
        self.GraphFrame.setBaseSize(QtCore.QSize(200, 200))
        self.GraphFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.GraphFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.GraphFrame.setObjectName("GraphFrame")
        self.LogGraph = QtGui.QGraphicsView(self.GraphFrame)
        self.LogGraph.setGeometry(QtCore.QRect(0, 0, 200, 200))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LogGraph.sizePolicy().hasHeightForWidth())
        self.LogGraph.setSizePolicy(sizePolicy)
        self.LogGraph.setMinimumSize(QtCore.QSize(200, 200))
        self.LogGraph.setMaximumSize(QtCore.QSize(200, 200))
        self.LogGraph.setBaseSize(QtCore.QSize(200, 200))
        self.LogGraph.setStyleSheet("background-image: url(:/img/log.png);")
        self.LogGraph.setObjectName("LogGraph")
        self.IDepth = QtGui.QLabel(self.GraphFrame)
        self.IDepth.setGeometry(QtCore.QRect(10, 90, 62, 18))
        self.IDepth.setObjectName("IDepth")
        self.ITime = QtGui.QLabel(self.GraphFrame)
        self.ITime.setGeometry(QtCore.QRect(90, 130, 62, 18))
        self.ITime.setObjectName("ITime")
        self.Top.addWidget(self.GraphFrame)
        self.InformationTabs = QtGui.QTabWidget(self.centralwidget)
        self.InformationTabs.setObjectName("InformationTabs")
        self.Information = QtGui.QWidget()
        self.Information.setObjectName("Information")
        self.widget = QtGui.QWidget(self.Information)
        self.widget.setGeometry(QtCore.QRect(9, 9, 261, 151))
        self.widget.setObjectName("widget")
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.LNumber = QtGui.QLabel(self.widget)
        self.LNumber.setObjectName("LNumber")
        self.gridLayout.addWidget(self.LNumber, 0, 0, 1, 1)
        self.INumber = QtGui.QLabel(self.widget)
        self.INumber.setObjectName("INumber")
        self.gridLayout.addWidget(self.INumber, 0, 1, 1, 1)
        self.LDate = QtGui.QLabel(self.widget)
        self.LDate.setObjectName("LDate")
        self.gridLayout.addWidget(self.LDate, 1, 0, 1, 1)
        self.IDate = QtGui.QLabel(self.widget)
        self.IDate.setObjectName("IDate")
        self.gridLayout.addWidget(self.IDate, 1, 1, 1, 1)
        self.LSight = QtGui.QLabel(self.widget)
        self.LSight.setObjectName("LSight")
        self.gridLayout.addWidget(self.LSight, 2, 0, 1, 1)
        self.ISight = QtGui.QLabel(self.widget)
        self.ISight.setObjectName("ISight")
        self.gridLayout.addWidget(self.ISight, 2, 1, 1, 1)
        self.LLead = QtGui.QLabel(self.widget)
        self.LLead.setObjectName("LLead")
        self.gridLayout.addWidget(self.LLead, 3, 0, 1, 1)
        self.ILead = QtGui.QLabel(self.widget)
        self.ILead.setObjectName("ILead")
        self.gridLayout.addWidget(self.ILead, 3, 1, 1, 1)
        self.LTemperature = QtGui.QLabel(self.widget)
        self.LTemperature.setObjectName("LTemperature")
        self.gridLayout.addWidget(self.LTemperature, 4, 0, 1, 1)
        self.ITemperature = QtGui.QLabel(self.widget)
        self.ITemperature.setObjectName("ITemperature")
        self.gridLayout.addWidget(self.ITemperature, 4, 1, 1, 1)
        self.InformationTabs.addTab(self.Information, "")
        self.ExtraInfo = QtGui.QWidget()
        self.ExtraInfo.setObjectName("ExtraInfo")
        self.widget1 = QtGui.QWidget(self.ExtraInfo)
        self.widget1.setGeometry(QtCore.QRect(9, 9, 251, 131))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtGui.QGridLayout(self.widget1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LTimeIn = QtGui.QLabel(self.widget1)
        self.LTimeIn.setObjectName("LTimeIn")
        self.gridLayout_2.addWidget(self.LTimeIn, 0, 0, 1, 1)
        self.ITimeIn = QtGui.QLabel(self.widget1)
        self.ITimeIn.setObjectName("ITimeIn")
        self.gridLayout_2.addWidget(self.ITimeIn, 0, 1, 1, 1)
        self.LTimeOut = QtGui.QLabel(self.widget1)
        self.LTimeOut.setObjectName("LTimeOut")
        self.gridLayout_2.addWidget(self.LTimeOut, 1, 0, 1, 1)
        self.ITimeOut = QtGui.QLabel(self.widget1)
        self.ITimeOut.setObjectName("ITimeOut")
        self.gridLayout_2.addWidget(self.ITimeOut, 1, 1, 1, 1)
        self.LBarIn = QtGui.QLabel(self.widget1)
        self.LBarIn.setObjectName("LBarIn")
        self.gridLayout_2.addWidget(self.LBarIn, 2, 0, 1, 1)
        self.IBarIn = QtGui.QLabel(self.widget1)
        self.IBarIn.setObjectName("IBarIn")
        self.gridLayout_2.addWidget(self.IBarIn, 2, 1, 1, 1)
        self.LBarOut = QtGui.QLabel(self.widget1)
        self.LBarOut.setObjectName("LBarOut")
        self.gridLayout_2.addWidget(self.LBarOut, 3, 0, 1, 1)
        self.IBarOut = QtGui.QLabel(self.widget1)
        self.IBarOut.setObjectName("IBarOut")
        self.gridLayout_2.addWidget(self.IBarOut, 3, 1, 1, 1)
        self.LBarUseage = QtGui.QLabel(self.widget1)
        self.LBarUseage.setObjectName("LBarUseage")
        self.gridLayout_2.addWidget(self.LBarUseage, 4, 0, 1, 1)
        self.IBarUseage = QtGui.QLabel(self.widget1)
        self.IBarUseage.setObjectName("IBarUseage")
        self.gridLayout_2.addWidget(self.IBarUseage, 4, 1, 1, 1)
        self.InformationTabs.addTab(self.ExtraInfo, "")
        self.Top.addWidget(self.InformationTabs)
        self.Right.addLayout(self.Top)
        self.Buttons = QtGui.QHBoxLayout()
        self.Buttons.setObjectName("Buttons")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Buttons.addItem(spacerItem)
        self.Delete = QtGui.QPushButton(self.centralwidget)
        self.Delete.setObjectName("Delete")
        self.Buttons.addWidget(self.Delete)
        self.Edit = QtGui.QPushButton(self.centralwidget)
        self.Edit.setObjectName("Edit")
        self.Buttons.addWidget(self.Edit)
        self.Right.addLayout(self.Buttons)
        self.INotes = QtGui.QTextBrowser(self.centralwidget)
        self.INotes.setObjectName("INotes")
        self.Right.addWidget(self.INotes)
        self.horizontalLayout.addLayout(self.Right)
        Dive.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Dive)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 819, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Dive.setMenuBar(self.menubar)
        self.AddDive = QtGui.QAction(Dive)
        self.AddDive.setObjectName("AddDive")
        self.Stats = QtGui.QAction(Dive)
        self.Stats.setObjectName("Stats")
        self.Quit = QtGui.QAction(Dive)
        self.Quit.setObjectName("Quit")
        self.About = QtGui.QAction(Dive)
        self.About.setObjectName("About")
        self.menuFile.addAction(self.AddDive)
        self.menuFile.addAction(self.Stats)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.Quit)
        self.menuHelp.addAction(self.About)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Dive)
        self.InformationTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dive)

    def retranslateUi(self, Dive):
        Dive.setWindowTitle(QtGui.QApplication.translate("Dive", "Diving Logbook", None, QtGui.QApplication.UnicodeUTF8))
        self.IDepth.setText(QtGui.QApplication.translate("Dive", "*depth*", None, QtGui.QApplication.UnicodeUTF8))
        self.ITime.setText(QtGui.QApplication.translate("Dive", "*Time*", None, QtGui.QApplication.UnicodeUTF8))
        self.LNumber.setText(QtGui.QApplication.translate("Dive", "Dive Number", None, QtGui.QApplication.UnicodeUTF8))
        self.INumber.setText(QtGui.QApplication.translate("Dive", "*RealNumber*", None, QtGui.QApplication.UnicodeUTF8))
        self.LDate.setText(QtGui.QApplication.translate("Dive", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.IDate.setText(QtGui.QApplication.translate("Dive", "*RealDate*", None, QtGui.QApplication.UnicodeUTF8))
        self.LSight.setText(QtGui.QApplication.translate("Dive", "Sight", None, QtGui.QApplication.UnicodeUTF8))
        self.ISight.setText(QtGui.QApplication.translate("Dive", "*RealSight*", None, QtGui.QApplication.UnicodeUTF8))
        self.LLead.setText(QtGui.QApplication.translate("Dive", "Lead", None, QtGui.QApplication.UnicodeUTF8))
        self.ILead.setText(QtGui.QApplication.translate("Dive", "*RealLead*", None, QtGui.QApplication.UnicodeUTF8))
        self.LTemperature.setText(QtGui.QApplication.translate("Dive", "Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.ITemperature.setText(QtGui.QApplication.translate("Dive", "*RealTemperature*", None, QtGui.QApplication.UnicodeUTF8))
        self.InformationTabs.setTabText(self.InformationTabs.indexOf(self.Information), QtGui.QApplication.translate("Dive", "Information", None, QtGui.QApplication.UnicodeUTF8))
        self.LTimeIn.setText(QtGui.QApplication.translate("Dive", "Time In", None, QtGui.QApplication.UnicodeUTF8))
        self.ITimeIn.setText(QtGui.QApplication.translate("Dive", "*RealTimeIn*", None, QtGui.QApplication.UnicodeUTF8))
        self.LTimeOut.setText(QtGui.QApplication.translate("Dive", "Time Out", None, QtGui.QApplication.UnicodeUTF8))
        self.ITimeOut.setText(QtGui.QApplication.translate("Dive", "*RealTimeOut*", None, QtGui.QApplication.UnicodeUTF8))
        self.LBarIn.setText(QtGui.QApplication.translate("Dive", "Bar In", None, QtGui.QApplication.UnicodeUTF8))
        self.IBarIn.setText(QtGui.QApplication.translate("Dive", "*RealBarIn*", None, QtGui.QApplication.UnicodeUTF8))
        self.LBarOut.setText(QtGui.QApplication.translate("Dive", "Bar Out", None, QtGui.QApplication.UnicodeUTF8))
        self.IBarOut.setText(QtGui.QApplication.translate("Dive", "*RealBarOut*", None, QtGui.QApplication.UnicodeUTF8))
        self.LBarUseage.setText(QtGui.QApplication.translate("Dive", "Bar Usage", None, QtGui.QApplication.UnicodeUTF8))
        self.IBarUseage.setText(QtGui.QApplication.translate("Dive", "*Bar usage*", None, QtGui.QApplication.UnicodeUTF8))
        self.InformationTabs.setTabText(self.InformationTabs.indexOf(self.ExtraInfo), QtGui.QApplication.translate("Dive", "Extra Information", None, QtGui.QApplication.UnicodeUTF8))
        self.Delete.setText(QtGui.QApplication.translate("Dive", "Delete Dive", None, QtGui.QApplication.UnicodeUTF8))
        self.Edit.setText(QtGui.QApplication.translate("Dive", "Edit Dive", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("Dive", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("Dive", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.AddDive.setText(QtGui.QApplication.translate("Dive", "Add Dive", None, QtGui.QApplication.UnicodeUTF8))
        self.Stats.setText(QtGui.QApplication.translate("Dive", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.Quit.setText(QtGui.QApplication.translate("Dive", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.About.setText(QtGui.QApplication.translate("Dive", "About", None, QtGui.QApplication.UnicodeUTF8))

import res_rc
