# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/window.ui'
#
# Created: Wed Aug 18 14:12:54 2010
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dive(object):
    def setupUi(self, Dive):
        Dive.setObjectName("Dive")
        Dive.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dive.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(Dive)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ListDives = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListDives.sizePolicy().hasHeightForWidth())
        self.ListDives.setSizePolicy(sizePolicy)
        self.ListDives.setMinimumSize(QtCore.QSize(200, 0))
        self.ListDives.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ListDives.setBaseSize(QtCore.QSize(200, 0))
        self.ListDives.setObjectName("ListDives")
        self.horizontalLayout.addWidget(self.ListDives)
        self.Right = QtGui.QVBoxLayout()
        self.Right.setObjectName("Right")
        self.GraphTab = QtGui.QHBoxLayout()
        self.GraphTab.setObjectName("GraphTab")
        self.GraphFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GraphFrame.sizePolicy().hasHeightForWidth())
        self.GraphFrame.setSizePolicy(sizePolicy)
        self.GraphFrame.setMinimumSize(QtCore.QSize(200, 200))
        self.GraphFrame.setMaximumSize(QtCore.QSize(200, 200))
        self.GraphFrame.setBaseSize(QtCore.QSize(200, 200))
        self.GraphFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.GraphFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.GraphFrame.setObjectName("GraphFrame")
        self.Graph = QtGui.QGraphicsView(self.GraphFrame)
        self.Graph.setGeometry(QtCore.QRect(0, 0, 200, 200))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Graph.sizePolicy().hasHeightForWidth())
        self.Graph.setSizePolicy(sizePolicy)
        self.Graph.setMinimumSize(QtCore.QSize(200, 200))
        self.Graph.setMaximumSize(QtCore.QSize(200, 200))
        self.Graph.setBaseSize(QtCore.QSize(200, 200))
        self.Graph.setStyleSheet("background-image: url(:/img/log.png);")
        self.Graph.setObjectName("Graph")
        self.IDepth = QtGui.QLabel(self.GraphFrame)
        self.IDepth.setGeometry(QtCore.QRect(10, 90, 62, 18))
        self.IDepth.setObjectName("IDepth")
        self.ITime = QtGui.QLabel(self.GraphFrame)
        self.ITime.setGeometry(QtCore.QRect(80, 130, 62, 18))
        self.ITime.setObjectName("ITime")
        self.GraphTab.addWidget(self.GraphFrame)
        self.Information = QtGui.QTabWidget(self.centralwidget)
        self.Information.setObjectName("Information")
        self.Global = QtGui.QWidget()
        self.Global.setObjectName("Global")
        self.layoutWidget = QtGui.QWidget(self.Global)
        self.layoutWidget.setGeometry(QtCore.QRect(-1, -1, 361, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.Holder = QtGui.QGridLayout(self.layoutWidget)
        self.Holder.setObjectName("Holder")
        self.LNumber = QtGui.QLabel(self.layoutWidget)
        self.LNumber.setObjectName("LNumber")
        self.Holder.addWidget(self.LNumber, 0, 0, 1, 1)
        self.INumber = QtGui.QLabel(self.layoutWidget)
        self.INumber.setObjectName("INumber")
        self.Holder.addWidget(self.INumber, 0, 1, 1, 1)
        self.LDate = QtGui.QLabel(self.layoutWidget)
        self.LDate.setObjectName("LDate")
        self.Holder.addWidget(self.LDate, 1, 0, 1, 1)
        self.IDate = QtGui.QLabel(self.layoutWidget)
        self.IDate.setObjectName("IDate")
        self.Holder.addWidget(self.IDate, 1, 1, 1, 1)
        self.LLead = QtGui.QLabel(self.layoutWidget)
        self.LLead.setObjectName("LLead")
        self.Holder.addWidget(self.LLead, 2, 0, 1, 1)
        self.ILead = QtGui.QLabel(self.layoutWidget)
        self.ILead.setObjectName("ILead")
        self.Holder.addWidget(self.ILead, 2, 1, 1, 1)
        self.LSight = QtGui.QLabel(self.layoutWidget)
        self.LSight.setObjectName("LSight")
        self.Holder.addWidget(self.LSight, 3, 0, 1, 1)
        self.ISight = QtGui.QLabel(self.layoutWidget)
        self.ISight.setObjectName("ISight")
        self.Holder.addWidget(self.ISight, 3, 1, 1, 1)
        self.LTemperature = QtGui.QLabel(self.layoutWidget)
        self.LTemperature.setObjectName("LTemperature")
        self.Holder.addWidget(self.LTemperature, 4, 0, 1, 1)
        self.ITemperature = QtGui.QLabel(self.layoutWidget)
        self.ITemperature.setObjectName("ITemperature")
        self.Holder.addWidget(self.ITemperature, 4, 1, 1, 1)
        self.Information.addTab(self.Global, "")
        self.InDepth = QtGui.QWidget()
        self.InDepth.setObjectName("InDepth")
        self.layoutWidget1 = QtGui.QWidget(self.InDepth)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 361, 211))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.Holder_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.Holder_2.setObjectName("Holder_2")
        self.LBarIn = QtGui.QLabel(self.layoutWidget1)
        self.LBarIn.setObjectName("LBarIn")
        self.Holder_2.addWidget(self.LBarIn, 0, 0, 1, 1)
        self.IBarIn = QtGui.QLabel(self.layoutWidget1)
        self.IBarIn.setObjectName("IBarIn")
        self.Holder_2.addWidget(self.IBarIn, 0, 1, 1, 1)
        self.LBarOut = QtGui.QLabel(self.layoutWidget1)
        self.LBarOut.setObjectName("LBarOut")
        self.Holder_2.addWidget(self.LBarOut, 1, 0, 1, 1)
        self.IBarOut = QtGui.QLabel(self.layoutWidget1)
        self.IBarOut.setObjectName("IBarOut")
        self.Holder_2.addWidget(self.IBarOut, 1, 1, 1, 1)
        self.LBarUseage = QtGui.QLabel(self.layoutWidget1)
        self.LBarUseage.setObjectName("LBarUseage")
        self.Holder_2.addWidget(self.LBarUseage, 2, 0, 1, 1)
        self.IBarUseage = QtGui.QLabel(self.layoutWidget1)
        self.IBarUseage.setObjectName("IBarUseage")
        self.Holder_2.addWidget(self.IBarUseage, 2, 1, 1, 1)
        self.LTimeIn = QtGui.QLabel(self.layoutWidget1)
        self.LTimeIn.setObjectName("LTimeIn")
        self.Holder_2.addWidget(self.LTimeIn, 3, 0, 1, 1)
        self.ITimeIn = QtGui.QLabel(self.layoutWidget1)
        self.ITimeIn.setObjectName("ITimeIn")
        self.Holder_2.addWidget(self.ITimeIn, 3, 1, 1, 1)
        self.LTimeOut = QtGui.QLabel(self.layoutWidget1)
        self.LTimeOut.setObjectName("LTimeOut")
        self.Holder_2.addWidget(self.LTimeOut, 4, 0, 1, 1)
        self.ITimeOut = QtGui.QLabel(self.layoutWidget1)
        self.ITimeOut.setObjectName("ITimeOut")
        self.Holder_2.addWidget(self.ITimeOut, 4, 1, 1, 1)
        self.Information.addTab(self.InDepth, "")
        self.GraphTab.addWidget(self.Information)
        self.Right.addLayout(self.GraphTab)
        self.Buttons = QtGui.QHBoxLayout()
        self.Buttons.setObjectName("Buttons")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Buttons.addItem(spacerItem)
        self.Edit = QtGui.QPushButton(self.centralwidget)
        self.Edit.setObjectName("Edit")
        self.Buttons.addWidget(self.Edit)
        self.Delete = QtGui.QPushButton(self.centralwidget)
        self.Delete.setObjectName("Delete")
        self.Buttons.addWidget(self.Delete)
        self.Right.addLayout(self.Buttons)
        self.INotes = QtGui.QTextBrowser(self.centralwidget)
        self.INotes.setObjectName("INotes")
        self.Right.addWidget(self.INotes)
        self.horizontalLayout.addLayout(self.Right)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        Dive.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Dive)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Dive.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Dive)
        self.statusbar.setObjectName("statusbar")
        Dive.setStatusBar(self.statusbar)
        self.AddDive = QtGui.QAction(Dive)
        self.AddDive.setObjectName("AddDive")
        self.Stats = QtGui.QAction(Dive)
        self.Stats.setObjectName("Stats")
        self.Quit = QtGui.QAction(Dive)
        self.Quit.setObjectName("Quit")
        self.About = QtGui.QAction(Dive)
        self.About.setObjectName("About")
        self.menuFile.addAction(self.AddDive)
        self.menuFile.addAction(self.Stats)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.Quit)
        self.menuHelp.addAction(self.About)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Dive)
        self.Information.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dive)

    def retranslateUi(self, Dive):
        Dive.setWindowTitle(QtGui.QApplication.translate("Dive", "Diving Logbook", None, QtGui.QApplication.UnicodeUTF8))
        self.IDepth.setText(QtGui.QApplication.translate("Dive", "*Depth*", None, QtGui.QApplication.UnicodeUTF8))
        self.ITime.setText(QtGui.QApplication.translate("Dive", "*Time*", None, QtGui.QApplication.UnicodeUTF8))
        self.LNumber.setText(QtGui.QApplication.translate("Dive", "Dive Number", None, QtGui.QApplication.UnicodeUTF8))
        self.INumber.setText(QtGui.QApplication.translate("Dive", "*Number*", None, QtGui.QApplication.UnicodeUTF8))
        self.LDate.setText(QtGui.QApplication.translate("Dive", "Dive Date", None, QtGui.QApplication.UnicodeUTF8))
        self.IDate.setText(QtGui.QApplication.translate("Dive", "*Date*", None, QtGui.QApplication.UnicodeUTF8))
        self.LLead.setText(QtGui.QApplication.translate("Dive", "Lead", None, QtGui.QApplication.UnicodeUTF8))
        self.ILead.setText(QtGui.QApplication.translate("Dive", "*Lead*", None, QtGui.QApplication.UnicodeUTF8))
        self.LSight.setText(QtGui.QApplication.translate("Dive", "Sight", None, QtGui.QApplication.UnicodeUTF8))
        self.ISight.setText(QtGui.QApplication.translate("Dive", "*sight*", None, QtGui.QApplication.UnicodeUTF8))
        self.LTemperature.setText(QtGui.QApplication.translate("Dive", "Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.ITemperature.setText(QtGui.QApplication.translate("Dive", "*Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.Information.setTabText(self.Information.indexOf(self.Global), QtGui.QApplication.translate("Dive", "Global Information", None, QtGui.QApplication.UnicodeUTF8))
        self.LBarIn.setText(QtGui.QApplication.translate("Dive", "Bar In", None, QtGui.QApplication.UnicodeUTF8))
        self.IBarIn.setText(QtGui.QApplication.translate("Dive", "*Bar In*", None, QtGui.QApplication.UnicodeUTF8))
        self.LBarOut.setText(QtGui.QApplication.translate("Dive", "Bar Out", None, QtGui.QApplication.UnicodeUTF8))
        self.IBarOut.setText(QtGui.QApplication.translate("Dive", "*Bar Out*", None, QtGui.QApplication.UnicodeUTF8))
        self.LBarUseage.setText(QtGui.QApplication.translate("Dive", "Bar Usage", None, QtGui.QApplication.UnicodeUTF8))
        self.IBarUseage.setText(QtGui.QApplication.translate("Dive", "*Useage*", None, QtGui.QApplication.UnicodeUTF8))
        self.LTimeIn.setText(QtGui.QApplication.translate("Dive", "Time In", None, QtGui.QApplication.UnicodeUTF8))
        self.ITimeIn.setText(QtGui.QApplication.translate("Dive", "*In*", None, QtGui.QApplication.UnicodeUTF8))
        self.LTimeOut.setText(QtGui.QApplication.translate("Dive", "Time Out", None, QtGui.QApplication.UnicodeUTF8))
        self.ITimeOut.setText(QtGui.QApplication.translate("Dive", "*out*", None, QtGui.QApplication.UnicodeUTF8))
        self.Information.setTabText(self.Information.indexOf(self.InDepth), QtGui.QApplication.translate("Dive", "Extra Information", None, QtGui.QApplication.UnicodeUTF8))
        self.Edit.setText(QtGui.QApplication.translate("Dive", "Edit Dive", None, QtGui.QApplication.UnicodeUTF8))
        self.Delete.setText(QtGui.QApplication.translate("Dive", "Delete Dive", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("Dive", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("Dive", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.AddDive.setText(QtGui.QApplication.translate("Dive", "Add Dive", None, QtGui.QApplication.UnicodeUTF8))
        self.Stats.setText(QtGui.QApplication.translate("Dive", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.Quit.setText(QtGui.QApplication.translate("Dive", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.About.setText(QtGui.QApplication.translate("Dive", "About", None, QtGui.QApplication.UnicodeUTF8))

import res_rc
